name: google_solution_challenge_fitness_app
description: A new Flutter project.

publish_to: 'none'


version: 1.0.0+1

environment:
  sdk: '>=2.18.6 <3.0.0'

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.2
  flutter_svg: ^1.1.6
  internet_connection_checker: ^0.0.1+4
  pedometer: ^3.0.0
  dartz: ^0.10.1
  equatable: ^2.0.5
  google_fonts: ^4.0.3

  flutter_tflite: ^1.0.1
  camera: ^0.10.3+2
  image:  ^3.2.0


dev_dependencies:
  flutter_lints: ^2.0.0
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true

  assets:
   - assets/tflite/
   - assets/images/
   - assets/icons/